name: 开发环境
env: development
project: vue-okzfans-template
app: vue-okzfans-template
host: vue-okzfans-template.com.cn
title: 开发环境
api:
  baseUrl: /dev-api # vue-admin-template 所使用 api
  identity: admin
  host: www.okzfans.top
  basePath: api/
version: 1.0.0
ico: null
timezone: +08:00
otherPath: you path