name: 测试环境
env: test
project: vue-okzfans-template
app: vue-okzfans-template
host: vue-okzfans-template.com.cn
title: 测试环境
api:
  baseUrl: vue-okzfans-template
  identity: admin
  host: vue-okzfans-template.com.cn
  basePath: api/
version: 1.0.0
ico: null
timezone: +08:00
cosPath: /admin/